import:
  - source: fepitre/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
  - source: fepitre/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: fepitre/qubes-continuous-integration:R4.1/travis-vms-rpm-r4.1.yml
  - source: fepitre/qubes-continuous-integration:R4.1/travis-vms-deb-r4.1.yml

jobs:
  include:
    - language: python
      python:
        - '3.7'
      install:
       - pip install --quiet -r ci/requirements.txt
      script:
       - PYTHONPATH=test-packages pylint --rcfile=ci/pylintrc qubesmanager
