os: linux
dist: bionic
language: generic
install:
  - git clone -b travis-log https://github.com/fepitre/qubes-builder ~/qubes-builder
script:
  - ~/qubes-builder/scripts/travis-build
  - ~/qubes-builder/scripts/travis-install
  - ~/qubes-builder/scripts/travis-reprotest
addons:
  apt:
    packages:
      - language-pack-en
branches:
  except:
    - /.*_.*/
    - build

import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml

jobs:
  include:
    - language: python
      python:
        - '3.7'
      install:
       - pip install --quiet -r ci/requirements.txt
      script:
       - PYTHONPATH=test-packages pylint --rcfile=ci/pylintrc qubesmanager
